# 2D Numpy in Python

### Create a 2D Numpy Array

In [1]:
# Import the libraries

import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Create a list

a = [[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# Show the numpy array dimensions

A.ndim

2

In [5]:
# Show the numpy array shape

A.shape

(3, 3)

In [6]:
# Show the numpy array size

A.size

9

### Accessing different elements of a Numpy Array

In [7]:
[[A[0,0],A[0,1],A[0,2]],[A[1,0],A[1,1],A[1,2]],[A[2,0],[2,1],[2,2]]]

[[11, 12, 13], [21, 22, 23], [31, [2, 1], [2, 2]]]

In [9]:
np.array([[A[0,0],A[0,1],A[0,2]],[A[1,0],A[1,1],A[1,2]],[A[2,0],[2,1],[2,2]]])

C:\Users\kbhas\AppData\Local\Temp\ipykernel_13776\2889121446.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[A[0,0],A[0,1],A[0,2]],[A[1,0],A[1,1],A[1,2]],[A[2,0],[2,1],[2,2]]])


array([[11, 12, 13],
       [21, 22, 23],
       [31, list([2, 1]), list([2, 2])]], dtype=object)

In [8]:
# Access the element on the second row and third column

A[1,2]

23

In [10]:
# Access the element on the second row and third column

A[1][2]

23

In [11]:
# Access the element on the first row and first column

A[0][0]

11

In [12]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [13]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

### Basic Operations

In [14]:
# Create a numpy array X

X = np.array([[1,0],[0,1]])
X

array([[1, 0],
       [0, 1]])

In [15]:
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [17]:
# Create a numpy array Y

Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [19]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [20]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [21]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [22]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [23]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [24]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [25]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [26]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [27]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])